FAQ.md

A patch to remove ZERO WIDTH SPACE, `0xE2 0x80 0x8B`.

remove ZERO WIDTH SPACE

---

FAQ.md

TeX commands installed through Cygwin do not work at all because LaTeX Workshop does not support path resolving for Cygwin.  See James-Yu/LaTeX-Workshop/issues/1143.

add faq on cygwin

---

FAQ.md

Add a FAQ that the directory ~/node_modules may cause errors on Mac and Linux. Related to James-Yu/LaTeX-Workshop/issues/1164.

faq on the directory ~/node_modules

---

Compile.md

I think there's a need to indicate the priority of magic comments over default recipe.

add a note on magic comments in LaTeX recipes

---

FAQ.md

This is a PR to clarify that Spell Right causes high CPU load issues.  James-Yu/LaTeX-Workshop/issues/1196 and James-Yu/LaTeX-Workshop/issues/1260.

add high CPU load issues

---

Compile.md

The link in the wiki sent you to the raw files page instead of the formatted version. I've fixed it here.

Fix Link to multi file projects

---

Remote.md
_Sidebar.md

We cannot stop users from using VS Code Remote Development extensions. What we can do is warning them.

add doc on VS Code Remote

---

View.md

With the new update, ```latex-workshop.view.pdf.external.command``` was broken to two segments, ```latex-workshop.view.pdf.external.viewer.command``` and ```latex-workshop.view.pdf.external.viewer.args```. 
I have updated the wiki accordingly. Hopefully, it makes sense. :)

latex-workshop.view.pdf.external.viewer.* update

---

Hover.md
View.md

#44 
- Add: `latex-workshop.texdoc.args`
- Add: `latex-workshop.texdoc.path`
- Remove: `latex-workshop.latex.texdoc.args`
- Remove: `latex-workshop.latex.texdoc.path`

Rename texdoc variables, fix small mistake

---

Environments.md
Snippets.md

Referencing: [#1716](https://github.com/James-Yu/LaTeX-Workshop/issues/1716) Folding arbitary regions using comments.
Add documentation to describe cold folding.

Describe code folding

---

Bibtex.md
_Sidebar.md

James-Yu/LaTeX-Workshop#1780 
I thought it was best to add a new file to keep bibtex features separate from latex features in the wiki.
This will require a corresponding link in the project [README](https://github.com/James-Yu/LaTeX-Workshop/blob/master/README.md).

Document bibtex sorting and aligning actions

---

FAQ.md

Add LaTeX Preview to the list of incompatible extensions.
Related to
- James-Yu/LaTeX-Workshop/issues/1283 
- https://tex.stackexchange.com/questions/527463/pdf-preview-in-visual-studio-code

Add LaTeX Preview to the list of incompatible extensions.

---

View.md

This adds an example synctex configuration for the default pdf viewer under KDE Plasma, Okular.
original source: https://miterion.de/post/vscodeplusokular/
modified to work with current vscode / latex-workshop

add okular synctex configuration

---

FAQ.md

I found that the "[Path Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense)" has the same effect as "[Path Autocomplete](https://marketplace.visualstudio.com/items?itemName=ionutvmi.path-autocomplete)" (breaking the bibliography completions), so I added it to the list of incompatible extensions.

Add "Path Intellisense" as incompatible extension

---

Install.md

This PR contains a simple fix for the wrongly spelled `officail` to `official`.

Fixed spelling `officail`

---

FAQ.md

In the FAQ, you already recommend vscode-languagetool for spell and grammar checking, which is abandoned. Using the same underlying engine, there is [valentjn/vscode-ltex](https://valentjn.github.io/ltex/) and I think that should be recommended instead. Searched for an edit button in the wiki itself, thanks for pointing me here.

Suggest LTeX for spell checking in FAQ

---

Intellisense.md

Fix default value for `latex-workshop.intellisense.package.enabled` in table.
The correct default value is `true`, see package.json below.
https://github.com/James-Yu/LaTeX-Workshop/blob/e85585e2bc0dd767e8e0887c452ec0a53ec23bad/package.json#L1840-L1845

Fix default value for `intellisense.package.enabled`

---

View.md

While trying to use Okular as an external editor, I realized this is not yet documented in your wiki. 
I found a [blog post](https://zhauniarovich.com/post/2023/2023-03-configuring-forward-and-inverse-search-in-latex-workshop-and-okular/) describing how it works and decided to propose this change to you :)

Document backward search for okular

---

ExtraFeatures.md

I needed this for my thesis that has subfiles which include other subfiles, and makes use of `texcount`s `%TC:fileinclude`.

Explain how to use `-inc` with `texcount`

---

Intellisense.md

See James-Yu/LaTeX-Workshop@aa27787a (Fix #4134 Add a new config `intellisense.subsuperscript.enabled`, 2024-01-15)

Add latex-workshop.intellisense.subsuperscript.enabled

---

Intellisense.md

See https://github.com/James-Yu/LaTeX-Workshop/commit/aa27787a (Fix #4134 Add a new config `intellisense.subsuperscript.enabled`, 2024-01-15)
Also update link to source of cwl files.

Add latex-workshop.intellisense.package.unusual
