- Hover.md
This is a patch to explain math preview on hover.
> math preview on hover

- FAQ.md
This is a patch to add FAQ on path containing Chinese characters.
> FAQ: path contains Chinese characters

- FAQ.md
- View.md
A patch to explain builtin synctex.
> add an explanation for built-in synctex.

- FAQ.md
- Install.md
- View.md
> Fix links.

- FAQ.md
This is a patch to add an entry on WSL.
> FAQ on WSL

- Hover.md
added entries for hover options
> add entries for hover options

- Hover.md
`$$` now supported on hover preview.
> $$ now supported on hover preview

- FAQ.md
FAQ entry related to James-Yu/LaTeX-Workshop/issues/988.
> FAQ entry on syntax highliting.

- FAQ.md
- Install.md
- _Sidebar.md
Recommend users to use Remote WSL and Remote Containers.
> recommend users to use Remote WSL and Remote Containers.

- Hover.md
- _Sidebar.md
> remove TikZ documents

- View.md
please squash the commits into one, sry for the noise
> view & synctex: zathura support

- Install.md
Word count feature now exists in LaTeX Utilities.
> Remove obsolete texcount documentation

- FAQ.md
Add an entry to install older version.
> install older version

- View.md
> Document synctex keybinding

- View.md
> Update configuration documentation for View.md

- Linters.md
#44 
- Add: `latex-workshop.chktex.delay`
- Add: `latex-workshop.chktex.run`
- Remove: `latex-workshop.chktex.interval`
> Update ChkTeX documentation

- Install.md
> the ways of setting PATH

- Compile.md
- _Sidebar.md
add a link to an entry on PATH
> add a link to an entry on PATH

- FAQ.md
add an entry noticing that code server is not supported.
> code server is not supported

- FAQ.md
add entries on Visual Studio Online and Live Share
> add entries on Visual Studio Online

- Compile.md
> Document progress.location

- Intellisense.md
> Document intellisense.preview.enabled

- FAQ.md
As discussed in https://github.com/James-Yu/LaTeX-Workshop/issues/1917, I have added a note about a temporary solution to fix WSL2 file watchers sync.
> WSL2 temporary fix note

- View.md
Add step to make files executable
> Update steps for evince

- View.md
Move settings details to the end of the file for the improvement of the readability.
> Restructuring View.md

- View.md
> fixing <kdb> .. </kbd>

- Compile.md
for `latex-workshop.latex.clean.method`
> Fixed markdown markup

- View.md
I've modified the documentation line for setting configs in SumatraPDF and VS Code.
> modification of the documentation part for reverse searching in SumatraPDF

- View.md
> Fix broken link for SumatraPDF discussion forum

- Install.md
All 4000+ packages, at ~8GB and 2h30 download/install time, are not needed..
> Install.md: add link to TinyTeX

- Compile.md
- ExtraFeatures.md
- Format.md
- View.md
> Add missing documentation

- Install.md
Also, I've reorganized it for clarity.
> Installation section updated to add more info for MiKTeX support

- Compile.md
texify has issues with BibLaTeX and biber
> Update Compile.md : texify has issues with BibLaTeX and biber

- ExtraFeatures.md
- FAQ.md
- _Sidebar.md
Docs for https://github.com/James-Yu/LaTeX-Workshop/pull/4308
> Live Share docs

- Format.md
> Update documentation for formatting.tex-fmt.args to correct argument name from `--tab` to `--tabsize`
